"use client"

import { useState } from "react"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import type { ParallaxConfig } from "@/lib/parallax-types"
import { generateHtml, generateCss, generateJs } from "@/lib/code-generator"
import { Copy, Check, Download, Code2, FileJson } from "lucide-react"

interface ExportModalProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  config: ParallaxConfig | null
}

type ExportFormat = "html" | "css" | "js"

export default function ExportModal({ open, onOpenChange, config }: ExportModalProps) {
  const [format, setFormat] = useState<ExportFormat>("html")
  const [copied, setCopied] = useState(false)

  if (!config) return null

  const getCode = () => {
    switch (format) {
      case "html": return generateHtml(config)
      case "css": return generateCss(config)
      case "js": return generateJs(config)
    }
  }

  const code = getCode()

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(code)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // Ignore clipboard errors
    }
  }

  const handleDownload = () => {
    const ext = format === "html" ? "html" : format === "css" ? "css" : "js"
    const blob = new Blob([code], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `parallax-scene.${ext}`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-3xl border-white/10 bg-[#0f0f0f] text-white">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 text-white">
            <Code2 className="h-5 w-5 text-[#F5C518]" />
            Export Parallax Code
          </DialogTitle>
          <DialogDescription className="text-white/50">
            Copy or download the generated {format.toUpperCase()} code for your parallax scene.
          </DialogDescription>
        </DialogHeader>

        <Tabs value={format} onValueChange={(v) => setFormat(v as ExportFormat)} className="w-full">
          <TabsList className="bg-white/5 border border-white/10 p-0.5 gap-0">
            <TabsTrigger
              value="html"
              className="text-xs gap-1.5 data-[state=active]:bg-[#F5C518] data-[state=active]:text-black rounded"
            >
              <Code2 className="h-3.5 w-3.5" />
              HTML
            </TabsTrigger>
            <TabsTrigger
              value="css"
              className="text-xs gap-1.5 data-[state=active]:bg-[#F5C518] data-[state=active]:text-black rounded"
            >
              <FileJson className="h-3.5 w-3.5" />
              CSS
            </TabsTrigger>
            <TabsTrigger
              value="js"
              className="text-xs gap-1.5 data-[state=active]:bg-[#F5C518] data-[state=active]:text-black rounded"
            >
              <FileJson className="h-3.5 w-3.5" />
              JS
            </TabsTrigger>
          </TabsList>

          <TabsContent value={format} className="mt-3">
            <div className="relative">
              <pre className="json-textarea w-full h-80 rounded-lg border border-white/10 bg-[#0a0a0a] p-4 overflow-auto text-xs leading-relaxed text-white/80 font-mono whitespace-pre">
                {code}
              </pre>
              <div className="absolute top-3 right-3 flex gap-1.5">
                <Button
                  size="sm"
                  variant="outline"
                  onClick={handleCopy}
                  className="h-8 text-xs gap-1.5 border-white/10 bg-white/5 hover:bg-white/10 text-white"
                >
                  {copied ? <Check className="h-3.5 w-3.5 text-green-400" /> : <Copy className="h-3.5 w-3.5" />}
                  {copied ? "Copied!" : "Copy"}
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  onClick={handleDownload}
                  className="h-8 text-xs gap-1.5 border-white/10 bg-white/5 hover:bg-white/10 text-white"
                >
                  <Download className="h-3.5 w-3.5" />
                  Download
                </Button>
              </div>
            </div>
          </TabsContent>
        </Tabs>

        <div className="flex items-center justify-between text-[10px] text-white/40 font-mono pt-2 border-t border-white/10">
          <span>{config.layers.length} layers · {config.effect} effect</span>
          <span>Generated by Readlyn</span>
        </div>
      </DialogContent>
    </Dialog>
  )
}
