import type { Metadata } from "next";
import LegalPage from "@/components/legal/LegalPage";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms governing your use of Readlyn.",
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" updated="July 6, 2026">
      <section>
        <h2 className="font-grotesk text-lg font-semibold text-white mb-2">
          Acceptance
        </h2>
        <p>
          By creating an account or using Readlyn, you agree to these terms. If
          you do not agree, do not use the service.
        </p>
      </section>

      <section>
        <h2 className="font-grotesk text-lg font-semibold text-white mb-2">
          The service
        </h2>
        <p>
          Readlyn is an AI-powered infographic generator currently offered free
          during early access. Features, limits, and availability may change as
          the product evolves. We make no guarantee of uptime or uninterrupted
          access.
        </p>
      </section>

      <section>
        <h2 className="font-grotesk text-lg font-semibold text-white mb-2">
          Your content
        </h2>
        <p>
          You retain ownership of the content you create. You are responsible
          for the prompts you submit and the infographics you publish. Do not
          use Readlyn to generate illegal, harmful, or infringing content.
        </p>
      </section>

      <section>
        <h2 className="font-grotesk text-lg font-semibold text-white mb-2">
          AI-generated output
        </h2>
        <p>
          Infographics are generated by a third-party AI model (Groq Llama 3.3
          70B). AI output may contain inaccuracies. You are responsible for
          reviewing and verifying any facts, statistics, or claims before
          publishing.
        </p>
      </section>

      <section>
        <h2 className="font-grotesk text-lg font-semibold text-white mb-2">
          Usage limits
        </h2>
        <p>
          Free accounts are subject to usage limits (project count and daily
          generation limits) as described on the pricing page. We may enforce
          rate limits to protect service stability.
        </p>
      </section>

      <section>
        <h2 className="font-grotesk text-lg font-semibold text-white mb-2">
          Account termination
        </h2>
        <p>
          You may delete your account at any time from Settings. We may suspend
          or terminate accounts that abuse the service, attempt to circumvent
          rate limits, or violate these terms.
        </p>
      </section>

      <section>
        <h2 className="font-grotesk text-lg font-semibold text-white mb-2">
          Disclaimer
        </h2>
        <p>
          Readlyn is provided &quot;as is&quot; without warranties of any kind.
          We are not liable for any damages arising from your use of the service
          or reliance on AI-generated content.
        </p>
      </section>

      <section>
        <h2 className="font-grotesk text-lg font-semibold text-white mb-2">
          Contact
        </h2>
        <p>
          Questions about these terms? Open an issue on{" "}
          <a
            href="https://github.com/MuhammadTanveerAbbas/Readlyn/issues"
            className="text-[var(--accent)] hover:underline"
            target="_blank"
            rel="noopener noreferrer"
          >
            GitHub
          </a>
          .
        </p>
      </section>
    </LegalPage>
  );
}
