import type { ParallaxConfig } from "./parallax-types"

export interface Preset {
  id: string
  name: string
  description: string
  config: ParallaxConfig
}

export const PRESETS: Preset[] = [
  {
    id: "mountain-landscape",
    name: "Mountain Landscape",
    description: "Layered mountains with sky and foreground",
    config: {
      perspective: 1000,
      scrollDuration: 1.2,
      effect: "parallax",
      backgroundColor: "#1a1a2e",
      layers: [
        {
          id: "p-sky",
          label: "Sky Gradient",
          imageUrl: "/img/parallax/sky.svg",
          depth: 0.05,
          offsetX: 0,
          offsetY: 0,
          scale: 1,
          opacity: 1,
          blendMode: "normal",
          visible: true,
        },
        {
          id: "p-mountains-far",
          label: "Far Mountains",
          imageUrl: "/img/parallax/mountains-far.svg",
          depth: 0.25,
          offsetX: 0,
          offsetY: 0,
          scale: 1.05,
          opacity: 1,
          blendMode: "normal",
          visible: true,
        },
        {
          id: "p-mountains-near",
          label: "Near Mountains",
          imageUrl: "/img/parallax/mountains-near.svg",
          depth: 0.55,
          offsetX: 0,
          offsetY: 0,
          scale: 1,
          opacity: 1,
          blendMode: "normal",
          visible: true,
        },
        {
          id: "p-ground",
          label: "Foreground Ground",
          imageUrl: "/img/parallax/ground.svg",
          depth: 0.85,
          offsetX: 0,
          offsetY: 0,
          scale: 1,
          opacity: 1,
          blendMode: "normal",
          visible: true,
        },
        {
          id: "p-trees",
          label: "Tree Silhouettes",
          imageUrl: "/img/parallax/trees.svg",
          depth: 0.95,
          offsetX: 0,
          offsetY: 0,
          scale: 1,
          opacity: 1,
          blendMode: "normal",
          visible: true,
        },
      ],
    },
  },
  {
    id: "cosmic-journey",
    name: "Cosmic Journey",
    description: "Deep space scene with stars, nebula, and planets",
    config: {
      perspective: 1200,
      scrollDuration: 1.5,
      effect: "parallax",
      backgroundColor: "#05050a",
      layers: [
        {
          id: "c-stars",
          label: "Star Field",
          imageUrl: "/img/parallax/stars.svg",
          depth: 0.05,
          offsetX: 0,
          offsetY: 0,
          scale: 1.2,
          opacity: 0.8,
          blendMode: "screen",
          visible: true,
        },
        {
          id: "c-nebula",
          label: "Nebula Glow",
          imageUrl: "/img/parallax/nebula.svg",
          depth: 0.2,
          offsetX: 0,
          offsetY: 0,
          scale: 1,
          opacity: 0.6,
          blendMode: "screen",
          visible: true,
        },
        {
          id: "c-planet",
          label: "Large Planet",
          imageUrl: "/img/parallax/planet.svg",
          depth: 0.5,
          offsetX: 0,
          offsetY: 0,
          scale: 1,
          opacity: 1,
          blendMode: "normal",
          visible: true,
        },
        {
          id: "c-asteroids",
          label: "Asteroid Field",
          imageUrl: "/img/parallax/asteroids.svg",
          depth: 0.75,
          offsetX: 0,
          offsetY: 0,
          scale: 1,
          opacity: 0.9,
          blendMode: "screen",
          visible: true,
        },
        {
          id: "c-foreground",
          label: "Space Debris",
          imageUrl: "/img/parallax/space-debris.svg",
          depth: 0.95,
          offsetX: 0,
          offsetY: 0,
          scale: 1,
          opacity: 1,
          blendMode: "screen",
          visible: true,
        },
      ],
    },
  },
  {
    id: "city-skyline",
    name: "City Skyline",
    description: "Urban cityscape with sky, buildings, and street",
    config: {
      perspective: 1000,
      scrollDuration: 1.0,
      effect: "parallax",
      backgroundColor: "#0a0a1a",
      layers: [
        {
          id: "city-sky",
          label: "Night Sky",
          imageUrl: "/img/parallax/city-sky.svg",
          depth: 0.05,
          offsetX: 0,
          offsetY: 0,
          scale: 1,
          opacity: 1,
          blendMode: "normal",
          visible: true,
        },
        {
          id: "city-buildings-far",
          label: "Distant Buildings",
          imageUrl: "/img/parallax/buildings-far.svg",
          depth: 0.3,
          offsetX: 0,
          offsetY: 0,
          scale: 1,
          opacity: 0.7,
          blendMode: "normal",
          visible: true,
        },
        {
          id: "city-buildings-near",
          label: "Close Buildings",
          imageUrl: "/img/parallax/buildings-near.svg",
          depth: 0.6,
          offsetX: 0,
          offsetY: 0,
          scale: 1,
          opacity: 0.9,
          blendMode: "normal",
          visible: true,
        },
        {
          id: "city-street",
          label: "Street Level",
          imageUrl: "/img/parallax/street.svg",
          depth: 0.85,
          offsetX: 0,
          offsetY: 0,
          scale: 1,
          opacity: 1,
          blendMode: "normal",
          visible: true,
        },
      ],
    },
  },
  {
    id: "underwater",
    name: "Underwater World",
    description: "Ocean depths with light rays, fish, and coral",
    config: {
      perspective: 1000,
      scrollDuration: 1.3,
      effect: "parallax",
      backgroundColor: "#001a2e",
      layers: [
        {
          id: "w-surface",
          label: "Water Surface",
          imageUrl: "/img/parallax/water-surface.svg",
          depth: 0.1,
          offsetX: 0,
          offsetY: 0,
          scale: 1,
          opacity: 0.5,
          blendMode: "screen",
          visible: true,
        },
        {
          id: "w-rays",
          label: "Light Rays",
          imageUrl: "/img/parallax/light-rays.svg",
          depth: 0.25,
          offsetX: 0,
          offsetY: 0,
          scale: 1,
          opacity: 0.4,
          blendMode: "screen",
          visible: true,
        },
        {
          id: "w-fish-far",
          label: "Distant Fish",
          imageUrl: "/img/parallax/fish-far.svg",
          depth: 0.45,
          offsetX: 0,
          offsetY: 0,
          scale: 1,
          opacity: 0.7,
          blendMode: "normal",
          visible: true,
        },
        {
          id: "w-coral",
          label: "Coral Reef",
          imageUrl: "/img/parallax/coral.svg",
          depth: 0.7,
          offsetX: 0,
          offsetY: 0,
          scale: 1,
          opacity: 1,
          blendMode: "normal",
          visible: true,
        },
        {
          id: "w-fish-near",
          label: "Near Fish",
          imageUrl: "/img/parallax/fish-near.svg",
          depth: 0.9,
          offsetX: 0,
          offsetY: 0,
          scale: 1,
          opacity: 1,
          blendMode: "normal",
          visible: true,
        },
      ],
    },
  },
  {
    id: "abstract-geometric",
    name: "Abstract Geometric",
    description: "Modern geometric shapes with gradient colors",
    config: {
      perspective: 800,
      scrollDuration: 0.8,
      effect: "parallax",
      backgroundColor: "#0a0a0a",
      layers: [
        {
          id: "g-bg",
          label: "Base Gradient",
          imageUrl: "/img/parallax/geo-bg.svg",
          depth: 0.1,
          offsetX: 0,
          offsetY: 0,
          scale: 1,
          opacity: 1,
          blendMode: "normal",
          visible: true,
        },
        {
          id: "g-shapes-1",
          label: "Back Shapes",
          imageUrl: "/img/parallax/geo-shapes-1.svg",
          depth: 0.3,
          offsetX: 0,
          offsetY: 0,
          scale: 1.1,
          opacity: 0.7,
          blendMode: "screen",
          visible: true,
        },
        {
          id: "g-shapes-2",
          label: "Mid Shapes",
          imageUrl: "/img/parallax/geo-shapes-2.svg",
          depth: 0.55,
          offsetX: 0,
          offsetY: 0,
          scale: 1,
          opacity: 0.85,
          blendMode: "screen",
          visible: true,
        },
        {
          id: "g-shapes-3",
          label: "Front Shapes",
          imageUrl: "/img/parallax/geo-shapes-3.svg",
          depth: 0.8,
          offsetX: 0,
          offsetY: 0,
          scale: 1,
          opacity: 1,
          blendMode: "normal",
          visible: true,
        },
      ],
    },
  },
  {
    id: "sunset-beach",
    name: "Sunset Beach",
    description: "Tropical beach at sunset with waves and palm trees",
    config: {
      perspective: 1000,
      scrollDuration: 1.1,
      effect: "parallax",
      backgroundColor: "#1a0a2e",
      layers: [
        {
          id: "b-sunset",
          label: "Sunset Sky",
          imageUrl: "/img/parallax/sunset-sky.svg",
          depth: 0.05,
          offsetX: 0,
          offsetY: 0,
          scale: 1,
          opacity: 1,
          blendMode: "normal",
          visible: true,
        },
        {
          id: "b-sun",
          label: "Sun",
          imageUrl: "/img/parallax/sun.svg",
          depth: 0.15,
          offsetX: 0,
          offsetY: 0,
          scale: 1,
          opacity: 1,
          blendMode: "screen",
          visible: true,
        },
        {
          id: "b-clouds",
          label: "Clouds",
          imageUrl: "/img/parallax/clouds.svg",
          depth: 0.3,
          offsetX: 0,
          offsetY: 0,
          scale: 1,
          opacity: 0.6,
          blendMode: "screen",
          visible: true,
        },
        {
          id: "b-ocean",
          label: "Ocean",
          imageUrl: "/img/parallax/ocean.svg",
          depth: 0.5,
          offsetX: 0,
          offsetY: 0,
          scale: 1,
          opacity: 0.8,
          blendMode: "normal",
          visible: true,
        },
        {
          id: "b-palms",
          label: "Palm Trees",
          imageUrl: "/img/parallax/palms.svg",
          depth: 0.8,
          offsetX: 0,
          offsetY: 0,
          scale: 1,
          opacity: 1,
          blendMode: "normal",
          visible: true,
        },
        {
          id: "b-sand",
          label: "Sand Foreground",
          imageUrl: "/img/parallax/sand.svg",
          depth: 0.95,
          offsetX: 0,
          offsetY: 0,
          scale: 1.1,
          opacity: 1,
          blendMode: "normal",
          visible: true,
        },
      ],
    },
  },
]
